### ISSUE TITLE
How do I get it to train using ImageNetVID?

### ISSUE THREAD

**Issue by danho47** [huanglianghua/siamfc-pytorch#38]
Change "seqs = GOT10k(root_dir, subset='train', return_meta=True)" in the original tool/train code to "seqs = ImageNetVID(root_dir, subset =('train', 'val'))", but "ValueError: num_samples should be a positive integer value, but got num_samples=0".

**Comment by JayJayBinks1** [comment]
The first time that you ran the program, you probably used the wrong root directory (the root_dir variable that the dataset resides in). If you haven't done so, double check that your root directory is correct. Once you've done so, delete the cache folder that was created when you first ran it.

The program first checks if there's a cache folder so that it doesn't have to load the whole dataset each time. So when you ran it the first time (supposedly with the wrong root directory) it cached 0 samples. When you ran it subsequent times, it went straight to the cache folder rather than checking your root_dir.

**Comment by danho47** [comment]
Thank you so much!!
It's solved.
